# Generated by Django 2.2.23 on 2021-05-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210530_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='maker',
            new_name='registerer',
        ),
        migrations.AddField(
            model_name='item',
            name='place',
            field=models.IntegerField(choices=[(1, 'キッチン下'), (2, '冷蔵庫横'), (3, '洗面台下'), (4, '下駄箱'), (5, 'その他')], default=5),
            preserve_default=False,
        ),
    ]
