# Generated by Django 2.2.23 on 2021-05-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210530_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='need',
            field=models.BooleanField(default=False, verbose_name='補充が必要か'),
        ),
    ]
