# Generated by Django 3.2.8 on 2021-10-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210530_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='place',
            field=models.IntegerField(choices=[(1, '下駄箱'), (2, 'パントリー'), (3, 'キッチン・冷蔵庫'), (4, '洗面台下'), (5, 'トイレ'), (6, 'リビング・たんす'), (7, 'その他')]),
        ),
    ]
