# Generated by Django 3.2.8 on 2021-10-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_item_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='place',
            field=models.IntegerField(choices=[(1, 'パントリー'), (2, 'キッチン・冷蔵庫'), (3, '洗面台下'), (4, 'トイレ'), (5, 'リビング・たんす'), (6, '下駄箱'), (7, 'その他')]),
        ),
    ]
